// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.17.3
// source: ChainBlockService.proto

package ChainBlockService

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	anypb "google.golang.org/protobuf/types/known/anypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Symbols defined in public import of google/protobuf/timestamp.proto.

type Timestamp = timestamppb.Timestamp

// Symbols defined in public import of google/protobuf/any.proto.

type Any = anypb.Any

type Page struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PageNumber int64 `protobuf:"varint,1,opt,name=pageNumber,proto3" json:"pageNumber"`
	PageSize   int64 `protobuf:"varint,2,opt,name=pageSize,proto3" json:"pageSize"`
}

func (x *Page) Reset() {
	*x = Page{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ChainBlockService_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Page) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Page) ProtoMessage() {}

func (x *Page) ProtoReflect() protoreflect.Message {
	mi := &file_ChainBlockService_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Page.ProtoReflect.Descriptor instead.
func (*Page) Descriptor() ([]byte, []int) {
	return file_ChainBlockService_proto_rawDescGZIP(), []int{0}
}

func (x *Page) GetPageNumber() int64 {
	if x != nil {
		return x.PageNumber
	}
	return 0
}

func (x *Page) GetPageSize() int64 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type GetChainTransactionInfoReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	HashValue   string `protobuf:"bytes,1,opt,name=hashValue,proto3" json:"hashValue"`
	ManagerId   int64  `protobuf:"varint,2,opt,name=managerId,proto3" json:"managerId"`
	OperateType string `protobuf:"bytes,3,opt,name=operateType,proto3" json:"operateType"`
}

func (x *GetChainTransactionInfoReq) Reset() {
	*x = GetChainTransactionInfoReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ChainBlockService_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetChainTransactionInfoReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetChainTransactionInfoReq) ProtoMessage() {}

func (x *GetChainTransactionInfoReq) ProtoReflect() protoreflect.Message {
	mi := &file_ChainBlockService_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetChainTransactionInfoReq.ProtoReflect.Descriptor instead.
func (*GetChainTransactionInfoReq) Descriptor() ([]byte, []int) {
	return file_ChainBlockService_proto_rawDescGZIP(), []int{1}
}

func (x *GetChainTransactionInfoReq) GetHashValue() string {
	if x != nil {
		return x.HashValue
	}
	return ""
}

func (x *GetChainTransactionInfoReq) GetManagerId() int64 {
	if x != nil {
		return x.ManagerId
	}
	return 0
}

func (x *GetChainTransactionInfoReq) GetOperateType() string {
	if x != nil {
		return x.OperateType
	}
	return ""
}

type GetChainTransactionInfoResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TransactionDetails string `protobuf:"bytes,1,opt,name=transactionDetails,proto3" json:"transactionDetails"`
}

func (x *GetChainTransactionInfoResp) Reset() {
	*x = GetChainTransactionInfoResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ChainBlockService_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetChainTransactionInfoResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetChainTransactionInfoResp) ProtoMessage() {}

func (x *GetChainTransactionInfoResp) ProtoReflect() protoreflect.Message {
	mi := &file_ChainBlockService_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetChainTransactionInfoResp.ProtoReflect.Descriptor instead.
func (*GetChainTransactionInfoResp) Descriptor() ([]byte, []int) {
	return file_ChainBlockService_proto_rawDescGZIP(), []int{2}
}

func (x *GetChainTransactionInfoResp) GetTransactionDetails() string {
	if x != nil {
		return x.TransactionDetails
	}
	return ""
}

type GetTxHashInfoReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	HashValue    string `protobuf:"bytes,1,opt,name=hashValue,proto3" json:"hashValue"`
	ManagerId    int64  `protobuf:"varint,2,opt,name=managerId,proto3" json:"managerId"`
	BusinessType string `protobuf:"bytes,3,opt,name=businessType,proto3" json:"businessType"`
}

func (x *GetTxHashInfoReq) Reset() {
	*x = GetTxHashInfoReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ChainBlockService_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetTxHashInfoReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTxHashInfoReq) ProtoMessage() {}

func (x *GetTxHashInfoReq) ProtoReflect() protoreflect.Message {
	mi := &file_ChainBlockService_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTxHashInfoReq.ProtoReflect.Descriptor instead.
func (*GetTxHashInfoReq) Descriptor() ([]byte, []int) {
	return file_ChainBlockService_proto_rawDescGZIP(), []int{3}
}

func (x *GetTxHashInfoReq) GetHashValue() string {
	if x != nil {
		return x.HashValue
	}
	return ""
}

func (x *GetTxHashInfoReq) GetManagerId() int64 {
	if x != nil {
		return x.ManagerId
	}
	return 0
}

func (x *GetTxHashInfoReq) GetBusinessType() string {
	if x != nil {
		return x.BusinessType
	}
	return ""
}

type GetTxHashInfoResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CurrentHash      string `protobuf:"bytes,1,opt,name=currentHash,proto3" json:"currentHash"`
	Data             string `protobuf:"bytes,2,opt,name=data,proto3" json:"data"`
	Description      string `protobuf:"bytes,3,opt,name=description,proto3" json:"description"`
	LastHash         string `protobuf:"bytes,4,opt,name=lastHash,proto3" json:"lastHash"`
	UploadNode       string `protobuf:"bytes,5,opt,name=uploadNode,proto3" json:"uploadNode"`
	UploadSuccessAt  int64  `protobuf:"varint,6,opt,name=uploadSuccessAt,proto3" json:"uploadSuccessAt"`
	UploaderAccount  string `protobuf:"bytes,7,opt,name=uploaderAccount,proto3" json:"uploaderAccount"`
	UploaderName     string `protobuf:"bytes,8,opt,name=uploaderName,proto3" json:"uploaderName"`
	UploaderRole     string `protobuf:"bytes,9,opt,name=uploaderRole,proto3" json:"uploaderRole"`
	UploaderRoleName string `protobuf:"bytes,10,opt,name=uploaderRoleName,proto3" json:"uploaderRoleName"`
}

func (x *GetTxHashInfoResp) Reset() {
	*x = GetTxHashInfoResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ChainBlockService_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetTxHashInfoResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTxHashInfoResp) ProtoMessage() {}

func (x *GetTxHashInfoResp) ProtoReflect() protoreflect.Message {
	mi := &file_ChainBlockService_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTxHashInfoResp.ProtoReflect.Descriptor instead.
func (*GetTxHashInfoResp) Descriptor() ([]byte, []int) {
	return file_ChainBlockService_proto_rawDescGZIP(), []int{4}
}

func (x *GetTxHashInfoResp) GetCurrentHash() string {
	if x != nil {
		return x.CurrentHash
	}
	return ""
}

func (x *GetTxHashInfoResp) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

func (x *GetTxHashInfoResp) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *GetTxHashInfoResp) GetLastHash() string {
	if x != nil {
		return x.LastHash
	}
	return ""
}

func (x *GetTxHashInfoResp) GetUploadNode() string {
	if x != nil {
		return x.UploadNode
	}
	return ""
}

func (x *GetTxHashInfoResp) GetUploadSuccessAt() int64 {
	if x != nil {
		return x.UploadSuccessAt
	}
	return 0
}

func (x *GetTxHashInfoResp) GetUploaderAccount() string {
	if x != nil {
		return x.UploaderAccount
	}
	return ""
}

func (x *GetTxHashInfoResp) GetUploaderName() string {
	if x != nil {
		return x.UploaderName
	}
	return ""
}

func (x *GetTxHashInfoResp) GetUploaderRole() string {
	if x != nil {
		return x.UploaderRole
	}
	return ""
}

func (x *GetTxHashInfoResp) GetUploaderRoleName() string {
	if x != nil {
		return x.UploaderRoleName
	}
	return ""
}

type GetMaxBlockNumberReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ManagerId    int64  `protobuf:"varint,1,opt,name=managerId,proto3" json:"managerId"`
	BusinessType string `protobuf:"bytes,2,opt,name=businessType,proto3" json:"businessType"`
}

func (x *GetMaxBlockNumberReq) Reset() {
	*x = GetMaxBlockNumberReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ChainBlockService_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetMaxBlockNumberReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMaxBlockNumberReq) ProtoMessage() {}

func (x *GetMaxBlockNumberReq) ProtoReflect() protoreflect.Message {
	mi := &file_ChainBlockService_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMaxBlockNumberReq.ProtoReflect.Descriptor instead.
func (*GetMaxBlockNumberReq) Descriptor() ([]byte, []int) {
	return file_ChainBlockService_proto_rawDescGZIP(), []int{5}
}

func (x *GetMaxBlockNumberReq) GetManagerId() int64 {
	if x != nil {
		return x.ManagerId
	}
	return 0
}

func (x *GetMaxBlockNumberReq) GetBusinessType() string {
	if x != nil {
		return x.BusinessType
	}
	return ""
}

type GetMaxBlockNumberResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MaxBlockNumber string `protobuf:"bytes,1,opt,name=maxBlockNumber,proto3" json:"maxBlockNumber"`
}

func (x *GetMaxBlockNumberResp) Reset() {
	*x = GetMaxBlockNumberResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ChainBlockService_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetMaxBlockNumberResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMaxBlockNumberResp) ProtoMessage() {}

func (x *GetMaxBlockNumberResp) ProtoReflect() protoreflect.Message {
	mi := &file_ChainBlockService_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMaxBlockNumberResp.ProtoReflect.Descriptor instead.
func (*GetMaxBlockNumberResp) Descriptor() ([]byte, []int) {
	return file_ChainBlockService_proto_rawDescGZIP(), []int{6}
}

func (x *GetMaxBlockNumberResp) GetMaxBlockNumber() string {
	if x != nil {
		return x.MaxBlockNumber
	}
	return ""
}

var File_ChainBlockService_proto protoreflect.FileDescriptor

var file_ChainBlockService_proto_rawDesc = []byte{
	0x0a, 0x17, 0x43, 0x68, 0x61, 0x69, 0x6e, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x53, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x11, 0x43, 0x68, 0x61, 0x69, 0x6e,
	0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x1a, 0x1f, 0x67, 0x6f,
	0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x74, 0x69,
	0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x19, 0x67,
	0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x61,
	0x6e, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x42, 0x0a, 0x04, 0x50, 0x61, 0x67, 0x65,
	0x12, 0x1e, 0x0a, 0x0a, 0x70, 0x61, 0x67, 0x65, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x0a, 0x70, 0x61, 0x67, 0x65, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72,
	0x12, 0x1a, 0x0a, 0x08, 0x70, 0x61, 0x67, 0x65, 0x53, 0x69, 0x7a, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x08, 0x70, 0x61, 0x67, 0x65, 0x53, 0x69, 0x7a, 0x65, 0x22, 0x7a, 0x0a, 0x1a,
	0x47, 0x65, 0x74, 0x43, 0x68, 0x61, 0x69, 0x6e, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74,
	0x69, 0x6f, 0x6e, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x71, 0x12, 0x1c, 0x0a, 0x09, 0x68, 0x61,
	0x73, 0x68, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x68,
	0x61, 0x73, 0x68, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x6d, 0x61, 0x6e, 0x61,
	0x67, 0x65, 0x72, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x6d, 0x61, 0x6e,
	0x61, 0x67, 0x65, 0x72, 0x49, 0x64, 0x12, 0x20, 0x0a, 0x0b, 0x6f, 0x70, 0x65, 0x72, 0x61, 0x74,
	0x65, 0x54, 0x79, 0x70, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x6f, 0x70, 0x65,
	0x72, 0x61, 0x74, 0x65, 0x54, 0x79, 0x70, 0x65, 0x22, 0x4d, 0x0a, 0x1b, 0x47, 0x65, 0x74, 0x43,
	0x68, 0x61, 0x69, 0x6e, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x49,
	0x6e, 0x66, 0x6f, 0x52, 0x65, 0x73, 0x70, 0x12, 0x2e, 0x0a, 0x12, 0x74, 0x72, 0x61, 0x6e, 0x73,
	0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x73, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x12, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e,
	0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x73, 0x22, 0x72, 0x0a, 0x10, 0x47, 0x65, 0x74, 0x54, 0x78,
	0x48, 0x61, 0x73, 0x68, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x71, 0x12, 0x1c, 0x0a, 0x09, 0x68,
	0x61, 0x73, 0x68, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09,
	0x68, 0x61, 0x73, 0x68, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x6d, 0x61, 0x6e,
	0x61, 0x67, 0x65, 0x72, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x6d, 0x61,
	0x6e, 0x61, 0x67, 0x65, 0x72, 0x49, 0x64, 0x12, 0x22, 0x0a, 0x0c, 0x62, 0x75, 0x73, 0x69, 0x6e,
	0x65, 0x73, 0x73, 0x54, 0x79, 0x70, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x62,
	0x75, 0x73, 0x69, 0x6e, 0x65, 0x73, 0x73, 0x54, 0x79, 0x70, 0x65, 0x22, 0xef, 0x02, 0x0a, 0x11,
	0x47, 0x65, 0x74, 0x54, 0x78, 0x48, 0x61, 0x73, 0x68, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x73,
	0x70, 0x12, 0x20, 0x0a, 0x0b, 0x63, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x74, 0x48, 0x61, 0x73, 0x68,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x63, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x74, 0x48,
	0x61, 0x73, 0x68, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x12, 0x20, 0x0a, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72,
	0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x64, 0x65,
	0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x1a, 0x0a, 0x08, 0x6c, 0x61, 0x73,
	0x74, 0x48, 0x61, 0x73, 0x68, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x6c, 0x61, 0x73,
	0x74, 0x48, 0x61, 0x73, 0x68, 0x12, 0x1e, 0x0a, 0x0a, 0x75, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x4e,
	0x6f, 0x64, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x75, 0x70, 0x6c, 0x6f, 0x61,
	0x64, 0x4e, 0x6f, 0x64, 0x65, 0x12, 0x28, 0x0a, 0x0f, 0x75, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x53,
	0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x41, 0x74, 0x18, 0x06, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0f,
	0x75, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x53, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x41, 0x74, 0x12,
	0x28, 0x0a, 0x0f, 0x75, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x65, 0x72, 0x41, 0x63, 0x63, 0x6f, 0x75,
	0x6e, 0x74, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0f, 0x75, 0x70, 0x6c, 0x6f, 0x61, 0x64,
	0x65, 0x72, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x22, 0x0a, 0x0c, 0x75, 0x70, 0x6c,
	0x6f, 0x61, 0x64, 0x65, 0x72, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0c, 0x75, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x65, 0x72, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x22, 0x0a,
	0x0c, 0x75, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x65, 0x72, 0x52, 0x6f, 0x6c, 0x65, 0x18, 0x09, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0c, 0x75, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x65, 0x72, 0x52, 0x6f, 0x6c,
	0x65, 0x12, 0x2a, 0x0a, 0x10, 0x75, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x65, 0x72, 0x52, 0x6f, 0x6c,
	0x65, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x09, 0x52, 0x10, 0x75, 0x70, 0x6c,
	0x6f, 0x61, 0x64, 0x65, 0x72, 0x52, 0x6f, 0x6c, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x22, 0x58, 0x0a,
	0x14, 0x47, 0x65, 0x74, 0x4d, 0x61, 0x78, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x4e, 0x75, 0x6d, 0x62,
	0x65, 0x72, 0x52, 0x65, 0x71, 0x12, 0x1c, 0x0a, 0x09, 0x6d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x72,
	0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x6d, 0x61, 0x6e, 0x61, 0x67, 0x65,
	0x72, 0x49, 0x64, 0x12, 0x22, 0x0a, 0x0c, 0x62, 0x75, 0x73, 0x69, 0x6e, 0x65, 0x73, 0x73, 0x54,
	0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x62, 0x75, 0x73, 0x69, 0x6e,
	0x65, 0x73, 0x73, 0x54, 0x79, 0x70, 0x65, 0x22, 0x3f, 0x0a, 0x15, 0x47, 0x65, 0x74, 0x4d, 0x61,
	0x78, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70,
	0x12, 0x26, 0x0a, 0x0e, 0x6d, 0x61, 0x78, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x4e, 0x75, 0x6d, 0x62,
	0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0e, 0x6d, 0x61, 0x78, 0x42, 0x6c, 0x6f,
	0x63, 0x6b, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x32, 0xda, 0x02, 0x0a, 0x11, 0x43, 0x68, 0x61,
	0x69, 0x6e, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x73,
	0x0a, 0x12, 0x47, 0x65, 0x74, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e,
	0x48, 0x61, 0x73, 0x68, 0x12, 0x2d, 0x2e, 0x43, 0x68, 0x61, 0x69, 0x6e, 0x42, 0x6c, 0x6f, 0x63,
	0x6b, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x47, 0x65, 0x74, 0x43, 0x68, 0x61, 0x69,
	0x6e, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x6e, 0x66, 0x6f,
	0x52, 0x65, 0x71, 0x1a, 0x2e, 0x2e, 0x43, 0x68, 0x61, 0x69, 0x6e, 0x42, 0x6c, 0x6f, 0x63, 0x6b,
	0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x47, 0x65, 0x74, 0x43, 0x68, 0x61, 0x69, 0x6e,
	0x54, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x6e, 0x66, 0x6f, 0x52,
	0x65, 0x73, 0x70, 0x12, 0x68, 0x0a, 0x1b, 0x47, 0x65, 0x74, 0x54, 0x78, 0x48, 0x61, 0x73, 0x68,
	0x49, 0x6e, 0x66, 0x6f, 0x42, 0x79, 0x42, 0x75, 0x73, 0x69, 0x6e, 0x65, 0x73, 0x73, 0x54, 0x79,
	0x70, 0x65, 0x12, 0x23, 0x2e, 0x43, 0x68, 0x61, 0x69, 0x6e, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x53,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x47, 0x65, 0x74, 0x54, 0x78, 0x48, 0x61, 0x73, 0x68,
	0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x71, 0x1a, 0x24, 0x2e, 0x43, 0x68, 0x61, 0x69, 0x6e, 0x42,
	0x6c, 0x6f, 0x63, 0x6b, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x47, 0x65, 0x74, 0x54,
	0x78, 0x48, 0x61, 0x73, 0x68, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x73, 0x70, 0x12, 0x66, 0x0a,
	0x11, 0x47, 0x65, 0x74, 0x4d, 0x61, 0x78, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x4e, 0x75, 0x6d, 0x62,
	0x65, 0x72, 0x12, 0x27, 0x2e, 0x43, 0x68, 0x61, 0x69, 0x6e, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x53,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x47, 0x65, 0x74, 0x4d, 0x61, 0x78, 0x42, 0x6c, 0x6f,
	0x63, 0x6b, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x52, 0x65, 0x71, 0x1a, 0x28, 0x2e, 0x43, 0x68,
	0x61, 0x69, 0x6e, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e,
	0x47, 0x65, 0x74, 0x4d, 0x61, 0x78, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x4e, 0x75, 0x6d, 0x62, 0x65,
	0x72, 0x52, 0x65, 0x73, 0x70, 0x42, 0x2d, 0x5a, 0x2b, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x2f, 0x43, 0x68, 0x61, 0x69, 0x6e, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x53, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x3b, 0x43, 0x68, 0x61, 0x69, 0x6e, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x53, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x50, 0x00, 0x50, 0x01, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_ChainBlockService_proto_rawDescOnce sync.Once
	file_ChainBlockService_proto_rawDescData = file_ChainBlockService_proto_rawDesc
)

func file_ChainBlockService_proto_rawDescGZIP() []byte {
	file_ChainBlockService_proto_rawDescOnce.Do(func() {
		file_ChainBlockService_proto_rawDescData = protoimpl.X.CompressGZIP(file_ChainBlockService_proto_rawDescData)
	})
	return file_ChainBlockService_proto_rawDescData
}

var file_ChainBlockService_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_ChainBlockService_proto_goTypes = []interface{}{
	(*Page)(nil),                        // 0: ChainBlockService.Page
	(*GetChainTransactionInfoReq)(nil),  // 1: ChainBlockService.GetChainTransactionInfoReq
	(*GetChainTransactionInfoResp)(nil), // 2: ChainBlockService.GetChainTransactionInfoResp
	(*GetTxHashInfoReq)(nil),            // 3: ChainBlockService.GetTxHashInfoReq
	(*GetTxHashInfoResp)(nil),           // 4: ChainBlockService.GetTxHashInfoResp
	(*GetMaxBlockNumberReq)(nil),        // 5: ChainBlockService.GetMaxBlockNumberReq
	(*GetMaxBlockNumberResp)(nil),       // 6: ChainBlockService.GetMaxBlockNumberResp
}
var file_ChainBlockService_proto_depIdxs = []int32{
	1, // 0: ChainBlockService.ChainBlockService.GetTransactionHash:input_type -> ChainBlockService.GetChainTransactionInfoReq
	3, // 1: ChainBlockService.ChainBlockService.GetTxHashInfoByBusinessType:input_type -> ChainBlockService.GetTxHashInfoReq
	5, // 2: ChainBlockService.ChainBlockService.GetMaxBlockNumber:input_type -> ChainBlockService.GetMaxBlockNumberReq
	2, // 3: ChainBlockService.ChainBlockService.GetTransactionHash:output_type -> ChainBlockService.GetChainTransactionInfoResp
	4, // 4: ChainBlockService.ChainBlockService.GetTxHashInfoByBusinessType:output_type -> ChainBlockService.GetTxHashInfoResp
	6, // 5: ChainBlockService.ChainBlockService.GetMaxBlockNumber:output_type -> ChainBlockService.GetMaxBlockNumberResp
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_ChainBlockService_proto_init() }
func file_ChainBlockService_proto_init() {
	if File_ChainBlockService_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_ChainBlockService_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Page); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ChainBlockService_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetChainTransactionInfoReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ChainBlockService_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetChainTransactionInfoResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ChainBlockService_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetTxHashInfoReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ChainBlockService_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetTxHashInfoResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ChainBlockService_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetMaxBlockNumberReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ChainBlockService_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetMaxBlockNumberResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_ChainBlockService_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_ChainBlockService_proto_goTypes,
		DependencyIndexes: file_ChainBlockService_proto_depIdxs,
		MessageInfos:      file_ChainBlockService_proto_msgTypes,
	}.Build()
	File_ChainBlockService_proto = out.File
	file_ChainBlockService_proto_rawDesc = nil
	file_ChainBlockService_proto_goTypes = nil
	file_ChainBlockService_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// ChainBlockServiceClient is the client API for ChainBlockService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ChainBlockServiceClient interface {
	GetTransactionHash(ctx context.Context, in *GetChainTransactionInfoReq, opts ...grpc.CallOption) (*GetChainTransactionInfoResp, error)
	GetTxHashInfoByBusinessType(ctx context.Context, in *GetTxHashInfoReq, opts ...grpc.CallOption) (*GetTxHashInfoResp, error)
	GetMaxBlockNumber(ctx context.Context, in *GetMaxBlockNumberReq, opts ...grpc.CallOption) (*GetMaxBlockNumberResp, error)
}

type chainBlockServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewChainBlockServiceClient(cc grpc.ClientConnInterface) ChainBlockServiceClient {
	return &chainBlockServiceClient{cc}
}

func (c *chainBlockServiceClient) GetTransactionHash(ctx context.Context, in *GetChainTransactionInfoReq, opts ...grpc.CallOption) (*GetChainTransactionInfoResp, error) {
	out := new(GetChainTransactionInfoResp)
	err := c.cc.Invoke(ctx, "/ChainBlockService.ChainBlockService/GetTransactionHash", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chainBlockServiceClient) GetTxHashInfoByBusinessType(ctx context.Context, in *GetTxHashInfoReq, opts ...grpc.CallOption) (*GetTxHashInfoResp, error) {
	out := new(GetTxHashInfoResp)
	err := c.cc.Invoke(ctx, "/ChainBlockService.ChainBlockService/GetTxHashInfoByBusinessType", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chainBlockServiceClient) GetMaxBlockNumber(ctx context.Context, in *GetMaxBlockNumberReq, opts ...grpc.CallOption) (*GetMaxBlockNumberResp, error) {
	out := new(GetMaxBlockNumberResp)
	err := c.cc.Invoke(ctx, "/ChainBlockService.ChainBlockService/GetMaxBlockNumber", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ChainBlockServiceServer is the server API for ChainBlockService service.
type ChainBlockServiceServer interface {
	GetTransactionHash(context.Context, *GetChainTransactionInfoReq) (*GetChainTransactionInfoResp, error)
	GetTxHashInfoByBusinessType(context.Context, *GetTxHashInfoReq) (*GetTxHashInfoResp, error)
	GetMaxBlockNumber(context.Context, *GetMaxBlockNumberReq) (*GetMaxBlockNumberResp, error)
}

// UnimplementedChainBlockServiceServer can be embedded to have forward compatible implementations.
type UnimplementedChainBlockServiceServer struct {
}

func (*UnimplementedChainBlockServiceServer) GetTransactionHash(context.Context, *GetChainTransactionInfoReq) (*GetChainTransactionInfoResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTransactionHash not implemented")
}
func (*UnimplementedChainBlockServiceServer) GetTxHashInfoByBusinessType(context.Context, *GetTxHashInfoReq) (*GetTxHashInfoResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTxHashInfoByBusinessType not implemented")
}
func (*UnimplementedChainBlockServiceServer) GetMaxBlockNumber(context.Context, *GetMaxBlockNumberReq) (*GetMaxBlockNumberResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetMaxBlockNumber not implemented")
}

func RegisterChainBlockServiceServer(s *grpc.Server, srv ChainBlockServiceServer) {
	s.RegisterService(&_ChainBlockService_serviceDesc, srv)
}

func _ChainBlockService_GetTransactionHash_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetChainTransactionInfoReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChainBlockServiceServer).GetTransactionHash(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ChainBlockService.ChainBlockService/GetTransactionHash",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChainBlockServiceServer).GetTransactionHash(ctx, req.(*GetChainTransactionInfoReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChainBlockService_GetTxHashInfoByBusinessType_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTxHashInfoReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChainBlockServiceServer).GetTxHashInfoByBusinessType(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ChainBlockService.ChainBlockService/GetTxHashInfoByBusinessType",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChainBlockServiceServer).GetTxHashInfoByBusinessType(ctx, req.(*GetTxHashInfoReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChainBlockService_GetMaxBlockNumber_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMaxBlockNumberReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChainBlockServiceServer).GetMaxBlockNumber(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ChainBlockService.ChainBlockService/GetMaxBlockNumber",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChainBlockServiceServer).GetMaxBlockNumber(ctx, req.(*GetMaxBlockNumberReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _ChainBlockService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "ChainBlockService.ChainBlockService",
	HandlerType: (*ChainBlockServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetTransactionHash",
			Handler:    _ChainBlockService_GetTransactionHash_Handler,
		},
		{
			MethodName: "GetTxHashInfoByBusinessType",
			Handler:    _ChainBlockService_GetTxHashInfoByBusinessType_Handler,
		},
		{
			MethodName: "GetMaxBlockNumber",
			Handler:    _ChainBlockService_GetMaxBlockNumber_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "ChainBlockService.proto",
}
